---
output:
  html_document:
    mathjax: null
    md_extensions: "-tex_math_dollars"
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    css: styles.css
params:
  lCharts: NA
  dfResults: NA
  dfMetrics: NA
  dfGroups: NA
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```


```{r, results='asis', echo=FALSE, message=FALSE, warning=FALSE}
library(gsm.core)
library(gsm.kri)
library(gt)

setup <- Report_Setup(
  dfResults = params$dfResults,
  dfMetrics = params$dfMetrics,
  dfGroups = params$dfGroups
)

```


---
title: "`r setup$GroupLevel` KRI Overview"
subtitle: "Study: `r setup$StudyLabel`"
date: "Snapshot Date: `r setup$SnapshotDate`"
---

::: {#overall-group-select .overall-group-select title="Selected group will be highlighted in all charts for all KRIs."}
:::

```{r, echo=FALSE, results='asis', fig.height=2}
Report_StudyInfo(params$dfGroups)
```

## Study Overview

::: flag-container
::: {.flag .flag-red}
<div> `r setup$red_kris` Red KRIs </div>
:::

::: {.flag .flag-amber}
<div> `r setup$amber_kris` Amber KRIs </div>
:::
:::

::: gsm-overview-table


```{r echo=FALSE, warning=FALSE, results = 'asis'}
# subset data on latest snapshot date
dfResults_current <- FilterByLatestSnapshotDate(params$dfResults)

GroupOverViz <- Widget_GroupOverview(
  dfResults = dfResults_current,
  dfMetrics = params$dfMetrics,
  dfGroups = params$dfGroups,
  strGroupLevel = setup$GroupLevel,
  strGroupSubset = switch(setup$GroupLevel,
    Site = 'red',
    'all'
  ),
  strGroupLabelKey = switch(setup$GroupLevel,
    Site = 'InvestigatorLastName',
    NULL
  )
)

overview_viz <- list(groupOverview = GroupOverViz)

# Add FlagOverTime Table if dfResults contains delta data
if (any(grepl("_Change", names(params$dfResults)))) {
  intSnapshots <- 12L # consider adding this as a parameter
  strSnapshotDates <- unique(params$dfResults$SnapshotDate) %>%
    sort(decreasing = TRUE) %>%
    head(intSnapshots)

  # Only include risk signals flagged at the most recent snapshot and the 12 most recent snapshots.
  dfResultsFlagged <- params$dfResults %>%
    FilterByFlags(bCurrentlyFlagged = TRUE) %>%
    dplyr::filter(
      .data$SnapshotDate %in% strSnapshotDates
    )

  overview_viz$flagOverTime <- Widget_FlagOverTime(
    dfResults = dfResultsFlagged,
    dfMetrics = params$dfMetrics,
    strGroupLevel = setup$GroupLevel,
    strFootnote = glue::glue(
      "Table displays the {
        length(strSnapshotDates)
      } most recent snapshots and only includes risk signals flagged in the most recent snapshot."
    ),
    bExcludeEver = TRUE
  )
}

Report_MetricCharts(overview_viz)
```

:::

```{r, echo=FALSE, results = 'asis'}

Report_OverviewText(
  lSetup = setup,
  dfResults = dfResults_current,
  lStudy = setup$lStudy
)


```



```{r flag-change-html, echo=FALSE, results='asis'}

# Add custom GroupLabel and MetricLabel values to dfResults
dfResults_delta <- dfResults_current %>%
  dplyr::left_join(params$dfMetrics %>% dplyr::select(MetricID, MetricName=Metric),
                   by = "MetricID") %>%
  dplyr::mutate(MetricLabel = dplyr::coalesce(MetricName, MetricID)) %>%
  add_Groups_metadata(
    params$dfGroups,
    setup$GroupLevel,
    setup$GroupLabelKey
  ) %>%
  dplyr::mutate(GroupLabel = paste0(GroupID," (",.data[[setup$GroupLabelKey]],")"))

# Render a list of newly changed flags if deltas are included in dfResults
Report_FlagChange(dfResults = dfResults_delta)
```

## Results

```{r, echo=FALSE, results='asis'}
## remove srs metrics from the list of metrics for results section
vMetrics <- unique(params$dfResults$MetricID)[grep("srs", unique(params$dfResults$MetricID), invert = TRUE)]

for (i in vMetrics) {
  lMetric <- params$dfMetrics %>% dplyr::filter(MetricID == i) %>% as.list

  print(htmltools::h3(lMetric$Metric))

  lChartsNoHeatmap <- params$lCharts[[lMetric$MetricID]]
  lChartsNoHeatmap <- lChartsNoHeatmap[names(lChartsNoHeatmap) != "Funnel Heatmap"]

  Report_MetricCharts(
    lCharts = lChartsNoHeatmap,
    strMetricID = lMetric$MetricID
  )

  print(htmltools::tags$br())

}

```

## Heatmap

```{r, echo=FALSE, results='asis'}
for (i in vMetrics) {
  lMetric <- params$dfMetrics %>% dplyr::filter(MetricID == i) %>% as.list
  chart <- params$lCharts[[lMetric$MetricID]][["Funnel Heatmap"]]
  if (!is.null(chart)) {
    print(htmltools::h3(lMetric$Metric))
    knitr::knit_print(chart) %>% attr("knit_meta") %>% knitr::knit_meta_add()
    cat("<div class='gsm-widget'>")
    cat(knitr::knit_print(htmltools::tagList(chart)))
    cat("</div>")
  }
}
```

## Metric Details
```{r, echo=FALSE, results='asis'}
#print dfMetrics table
params$dfMetrics %>%
  gt::gt()
```

```{r echo=FALSE}
group_dropdown <- system.file('report', 'lib', 'overallGroupDropdown.js', package = "gsm.kri")
dropdown_drag <- system.file('report', 'lib', 'dragOverallGroupDropdown.js', package = "gsm.kri")
toggle_toc <- system.file('report', 'lib', 'toggleTOC.js', package = "gsm.kri")
```

```{js, file={group_dropdown}, echo=FALSE}
```

```{js, file={dropdown_drag}, echo=FALSE}
```

```{js, file={toggle_toc}, echo=FALSE}
```

```{js, file=system.file('report', 'lib', 'toggleChanges.js', package = 'gsm.kri'), echo=FALSE}
```
