---
title: "Funnel Plot"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Funnel Plot}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE}
library(gsm.timez)
library(dplyr)
```

```{r data-prep}
dfSubjects <- clindata::rawplus_dm
dfNumerator <- clindata::rawplus_ae
dfDenominator <- clindata::rawplus_visdt %>%
  dplyr::mutate(visit_dt = as.Date(visit_dt, "%Y-%m-%d"))
```

```{r timeline}
dfTimeline <- Timeline(
  dfSubjects = dfSubjects,
  dfNumerator = dfNumerator,
  dfDenominator = dfDenominator,
  strGroupCol = "invid",
  strSubjectCol = "subjid",
  strNumeratorDateCol = "aest_dt",
  strDenominatorDateCol = "visit_dt"
)
```

```{r analyze}
dfAnalyzed <- dfTimeline %>% TimeZScoreFunnel()
```

```{r flag}
dfFlagged <- dfAnalyzed %>% Flag(vThreshold = c(-1.5, -1, 2, 3))
```

```{r bounds}
dfBounds <- TimeZScoreFunnel_PredictBounds(dfAnalyzed, vThreshold = c(-1.5, -1, 2, 3))
```

```{r visualize, fig.width=10, fig.height=12}
VisualizeFunnel(dfFlagged)
```

```{r funnel-plot-last, fig.width=8, fig.height=6}
VisualizeFunnelPlot(dfFlagged, dfBounds)
```

```{r funnel-plot-early, fig.width=8, fig.height=6}
VisualizeFunnelPlot(dfFlagged, dfBounds, NMonth = 12)
```

```{r visualize-site-overreporting, fig.width=8, fig.height=6}
strSiteID_overreporting <- dfFlagged %>%
  dplyr::group_by(GroupID) %>%
  dplyr::mutate(n_months = n()) %>%
  dplyr::filter(NMonth == max(NMonth)) %>%
  dplyr::ungroup() %>%
  dplyr::filter(Flag > 0) %>%
  dplyr::arrange(desc(n_months)) %>%
  dplyr::pull(GroupID) %>%
  head(1)

VisualizeSite(dfFlagged, strSiteID = strSiteID_overreporting)
```

```{r visualize-site-underreporting, fig.width=8, fig.height=6}
strSiteID_underreporting <- dfFlagged %>%
  dplyr::group_by(GroupID) %>%
  dplyr::mutate(n_months = n()) %>%
  dplyr::filter(NMonth == max(NMonth)) %>%
  dplyr::ungroup() %>%
  dplyr::filter(Flag < 0) %>%
  dplyr::arrange(desc(n_months)) %>%
  dplyr::pull(GroupID) %>%
  head(1)

VisualizeSite(dfFlagged, strSiteID = strSiteID_underreporting)
```

```{r visualize-site-recovered-overreporting, fig.width=8, fig.height=6}
strSiteID_recovered_overreporting <- dfFlagged %>%
  dplyr::group_by(GroupID) %>%
  dplyr::mutate(n_months = n()) %>%
  dplyr::filter(any(Flag > 0)) %>%
  dplyr::filter(NMonth == max(NMonth)) %>%
  dplyr::filter(Flag == 0) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(desc(n_months)) %>%
  dplyr::pull(GroupID) %>%
  head(1)

VisualizeSite(dfFlagged, strSiteID = strSiteID_recovered_overreporting)
```

```{r visualize-site-recovered-underreporting, fig.width=8, fig.height=6}
strSiteID_recovered_underreporting <- dfFlagged %>%
  dplyr::group_by(GroupID) %>%
  dplyr::mutate(n_months = n()) %>%
  dplyr::filter(any(Flag < 0)) %>%
  dplyr::filter(NMonth == max(NMonth)) %>%
  dplyr::filter(Flag == 0) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(desc(n_months)) %>%
  dplyr::pull(GroupID) %>%
  head(1)

VisualizeSite(dfFlagged, strSiteID = strSiteID_recovered_underreporting)
```
